server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/oneapi?useUnicode=true&useSSL=false&characterEncoding=utf-8


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  check-config-location: false
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?

api-client:
  access-key: aaaaaa
  secret-key: bbbbbb
